# docker-compose.yml
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: moderation-backend
    ports:
      - "8000:8000"
    environment:
      MODEL_KEY: bart-large-mnli
      DEFAULT_THRESHOLD: "0.7"
      HF_HOME: /hf-cache
    volumes:
      - hf_cache:/hf-cache
      - ./backend:/app
    # If you want backend hot reload, uncomment:
    # command: ["uvicorn","main:app","--host","0.0.0.0","--port","8000","--reload"]

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: moderation-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      # Helps file watching on Windows bind mounts
      CHOKIDAR_USEPOLLING: "true"
    # Use Webpack instead of Turbopack in dev
    command: ["npm", "run", "dev"]
    volumes:
      # Bind your source for hot reload
      - ./frontend:/app
      # Keep node_modules INSIDE the container so binaries match the container's Node
      - /app/node_modules

volumes:
  hf_cache:
